#!/bin/bash

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

if [[ ! -z "${1##[0-9]*}" || -z $1 ]]; then
	echo "Parameter must be a value in MB."
	exit 1
fi



if [[ ! -z $(grep -ir "mailcow site configuration" /etc/nginx/sites-available/ 2> /dev/null) ]]; then
	sed -i "/upload_max_filesize/c\php_admin_value[upload_max_filesize] = ${1}M" /etc/php5/fpm/pool.d/mail.conf
	sed -i "/post_max_size/c\php_admin_value[post_max_size] = $(expr $1 + 1)M" /etc/php5/fpm/pool.d/mail.conf
	sed -i "s/client_max_body_size.*/client_max_body_size ${1}m;/g" /etc/nginx/sites-available/mailcow
	sed -i "s/message_size_limit.*/message_size_limit = $(( $1 * 1048576 ))/g" /etc/postfix/main.cf
	echo "Reloading services..."
	postfix reload
	nginx -s reload
	service php5-fpm reload
elif [[ ! -z $(grep -ir "mailcow site configuration" /etc/apache2/sites-available/ 2> /dev/null) ]]; then
	sed -i "/upload_max_filesize/c\php_value upload_max_filesize ${1}M" /etc/apache2/sites-available/mailcow.conf
	sed -i "/post_max_size/c\php_value post_max_size $(expr $1 + 1)M"  /etc/apache2/sites-available/mailcow.conf
	sed -i "s/message_size_limit.*/message_size_limit = $(( $1 * 1048576 ))/g" /etc/postfix/main.cf
	echo "Reloading services..."
	postfix reload
	service apache2 reload
else
	echo "Error: cannot find site configuration"
	exit 1
fi
